language: cpp
dist: trusty
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_03ff56ac6b2e_key -iv $encrypted_03ff56ac6b2e_iv
  -in travis/travisci_builder_id_key.enc -out travis/travisci_builder_id_key -d
- chmod 600 travis/travisci_builder_id_key
cache: ccache
install: travis/install_deps.sh
script: travis/compile.sh
env:
- PLATFORM="native_static"
- PLATFORM="native_dyn"
- PLATFORM="win32_static"
- PLATFORM="win32_dyn"
addons:
  ssh_known_hosts: download.kiwix.org
